In [12]:
#importing libraries
import numpy as np
import pandas as pd

In [20]:
data = np.arange(24).reshape(4,6)  #arange is a built-in function    #reshape makes a matrix   #without reshape data is in 1-D

In [10]:
data

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
print(type(data))

<class 'numpy.ndarray'>


In [17]:
data1 = np.arange(30,60).reshape(3,10)    #.arange(inclusive,exclusive)

In [14]:
data1

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [18]:
#checking shape or matrix
data1.shape

(3, 10)

In [16]:
#checking dimension
data1.ndim

2

In [24]:
data1 = np.linspace(20,10,4)   #starts from 20, ends at 10, divides into 4 equal parts

In [23]:
data1

array([20.        , 16.66666667, 13.33333333, 10.        ])

In [26]:
#generating random integer
np.random.randint(10)

4

In [27]:
df = pd.DataFrame(data1)

In [28]:
df

0
0  20.000000
1  16.666667
2  13.333333
3  10.000000

In [29]:
data = np.arange(30,60).reshape(5,6)

In [30]:
data

array([[30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [34]:
#creating a dataframe from array
df = pd.DataFrame(data)

In [33]:
df

0   1   2   3   4   5
0  30  31  32  33  34  35
1  36  37  38  39  40  41
2  42  43  44  45  46  47
3  48  49  50  51  52  53
4  54  55  56  57  58  59

In [38]:
#naming rows and columns
df = pd.DataFrame(data,index=['row1','row2','row3','row4','row5'],columns=['column1','column2','column3','column4','column5','column6'])

In [37]:
df

column1  column2  column3  column4  column5  column6
row1       30       31       32       33       34       35
row2       36       37       38       39       40       41
row3       42       43       44       45       46       47
row4       48       49       50       51       52       53
row5       54       55       56       57       58       59

In [39]:
#printing column name
df.columns

Index(['column1', 'column2', 'column3', 'column4', 'column5', 'column6'], dtype='object')

In [40]:
#no. of rows and columns
df.shape

(5, 6)

In [41]:
#retrieves first 5 rows
df.head()

column1  column2  column3  column4  column5  column6
row1       30       31       32       33       34       35
row2       36       37       38       39       40       41
row3       42       43       44       45       46       47
row4       48       49       50       51       52       53
row5       54       55       56       57       58       59

In [42]:
#retrieves last 5 rows
df.tail()

column1  column2  column3  column4  column5  column6
row1       30       31       32       33       34       35
row2       36       37       38       39       40       41
row3       42       43       44       45       46       47
row4       48       49       50       51       52       53
row5       54       55       56       57       58       59

In [43]:
#retrieves single random row
df.sample()

column1  column2  column3  column4  column5  column6
row4       48       49       50       51       52       53

In [45]:
#retrieves random no. of row
df.sample(3)

column1  column2  column3  column4  column5  column6
row3       42       43       44       45       46       47
row5       54       55       56       57       58       59
row4       48       49       50       51       52       53

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  5 non-null      int32
 1   column2  5 non-null      int32
 2   column3  5 non-null      int32
 3   column4  5 non-null      int32
 4   column5  5 non-null      int32
 5   column6  5 non-null      int32
dtypes: int32(6)
memory usage: 160.0+ bytes


In [48]:
df.describe()

column1    column2    column3    column4    column5    column6
count   5.000000   5.000000   5.000000   5.000000   5.000000   5.000000
mean   42.000000  43.000000  44.000000  45.000000  46.000000  47.000000
std     9.486833   9.486833   9.486833   9.486833   9.486833   9.486833
min    30.000000  31.000000  32.000000  33.000000  34.000000  35.000000
25%    36.000000  37.000000  38.000000  39.000000  40.000000  41.000000
50%    42.000000  43.000000  44.000000  45.000000  46.000000  47.000000
75%    48.000000  49.000000  50.000000  51.000000  52.000000  53.000000
max    54.000000  55.000000  56.000000  57.000000  58.000000  59.000000

In [49]:
# Generating sample Google Play Store data
data = {
    'App': [f'App_{i}' for i in range(1, 31)],
    'Category': np.random.choice(['Game', 'Productivity', 'Health', 'Education'], 30),
    'Rating': np.random.uniform(1.0, 5.0, 30).round(1),
    'Reviews': np.random.randint(1, 10000, 30),
    'Size': np.random.choice(['Varies with device', '10M', '20M', '30M'], 30),
    'Installs': np.random.choice(['1,000+', '10,000+', '50,000+', '100,000+'], 30),
    'Type': np.random.choice(['Free', 'Paid'], 30),
    'Price': np.random.choice(['0', '0.99', '1.99', '2.99', '4.99', '5.99', '9.99'], 30),
    'Content Rating': np.random.choice(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+'], 30)
}

In [50]:
data

{'App': ['App_1',
  'App_2',
  'App_3',
  'App_4',
  'App_5',
  'App_6',
  'App_7',
  'App_8',
  'App_9',
  'App_10',
  'App_11',
  'App_12',
  'App_13',
  'App_14',
  'App_15',
  'App_16',
  'App_17',
  'App_18',
  'App_19',
  'App_20',
  'App_21',
  'App_22',
  'App_23',
  'App_24',
  'App_25',
  'App_26',
  'App_27',
  'App_28',
  'App_29',
  'App_30'],
 'Category': array(['Game', 'Game', 'Health', 'Game', 'Education', 'Education',
        'Health', 'Game', 'Productivity', 'Health', 'Health', 'Education',
        'Game', 'Health', 'Health', 'Productivity', 'Game', 'Productivity',
        'Productivity', 'Productivity', 'Game', 'Health', 'Health', 'Game',
        'Education', 'Game', 'Game', 'Health', 'Health', 'Productivity'],
       dtype='<U12'),
 'Rating': array([2.2, 3.3, 3.5, 4.6, 3.5, 3.7, 3.4, 2.1, 3.7, 4.4, 2.7, 2. , 4.9,
        4.4, 2.7, 2.5, 3.3, 3.9, 3.7, 4.6, 3.1, 2.9, 3.8, 4. , 4.8, 4.5,
        3.5, 1.9, 3.1, 4.4]),
 'Reviews': array([6540, 8216, 3645, 2421, 5788, 357

In [51]:
df = pd.DataFrame(data)

In [52]:
df

App      Category  Rating  Reviews                Size  Installs  Type  \
0    App_1          Game     2.2     6540                 20M   10,000+  Paid   
1    App_2          Game     3.3     8216                 20M   50,000+  Free   
2    App_3        Health     3.5     3645                 10M   10,000+  Free   
3    App_4          Game     4.6     2421                 20M    1,000+  Paid   
4    App_5     Education     3.5     5788  Varies with device  100,000+  Free   
5    App_6     Education     3.7     3575                 10M   10,000+  Free   
6    App_7        Health     3.4     6639                 30M    1,000+  Free   
7    App_8          Game     2.1     5959  Varies with device   50,000+  Paid   
8    App_9  Productivity     3.7      446                 30M  100,000+  Paid   
9   App_10        Health     4.4     3915                 20M   10,000+  Free   
10  App_11        Health     2.7     9656                 30M   50,000+  Free   
11  App_12     Education     2.0     6818                 10M  100,000+  Free   
12  App_13          Game     4.9     8117                 20M    1,000+  Free   
13  App_14        Health     4.4     2676  Varies with device   50,000+  Free   
14  App_15        Health     2.7     9184                 20M   50,000+  Paid   
15  App_16  Productivity     2.5     4030                 10M    1,000+  Paid   
16  App_17          Game     3.3     8800  Varies with device  100,000+  Paid   
17  App_18  Productivity     3.9     5051                 30M    1,000+  Paid   
18  App_19  Productivity     3.7     3434  Varies with device  100,000+  Paid   
19  App_20  Productivity     4.6     8468                 10M    1,000+  Paid   
20  App_21          Game     3.1     5399  Varies with device    1,000+  Paid   
21  App_22        Health     2.9     8500                 10M   10,000+  Paid   
22  App_23        Health     3.8     9590                 20M  100,000+  Paid   
23  App_24          Game     4.0      434                 30M  100,000+  Free   
24  App_25     Education     4.8     1836                 20M   10,000+  Free   
25  App_26          Game     4.5     9497                 30M    1,000+  Free   
26  App_27          Game     3.5       61                 30M  100,000+  Paid   
27  App_28        Health     1.9     5883  Varies with device   10,000+  Free   
28  App_29        Health     3.1     4672                 10M  100,000+  Free   
29  App_30  Productivity     4.4     4346  Varies with device    1,000+  Paid   

   Price Content Rating  
0   1.99     Mature 17+  
1      0   Everyone 10+  
2   2.99     Mature 17+  
3      0           Teen  
4   2.99           Teen  
5   4.99           Teen  
6   4.99       Everyone  
7      0       Everyone  
8   9.99     Mature 17+  
9   4.99     Mature 17+  
10  9.99       Everyone  
11     0       Everyone  
12     0       Everyone  
13  5.99       Everyone  
14  9.99     Mature 17+  
15  0.99       Everyone  
16     0   Everyone 10+  
17     0       Everyone  
18  2.99       Everyone  
19  2.99     Mature 17+  
20  4.99   Everyone 10+  
21  0.99           Teen  
22  5.99     Mature 17+  
23  2.99           Teen  
24  9.99           Teen  
25  5.99           Teen  
26  9.99   Everyone 10+  
27  0.99   Everyone 10+  
28     0       Everyone  
29     0           Teen

In [53]:
df.head()

App   Category  Rating  Reviews                Size  Installs  Type  \
0  App_1       Game     2.2     6540                 20M   10,000+  Paid   
1  App_2       Game     3.3     8216                 20M   50,000+  Free   
2  App_3     Health     3.5     3645                 10M   10,000+  Free   
3  App_4       Game     4.6     2421                 20M    1,000+  Paid   
4  App_5  Education     3.5     5788  Varies with device  100,000+  Free   

  Price Content Rating  
0  1.99     Mature 17+  
1     0   Everyone 10+  
2  2.99     Mature 17+  
3     0           Teen  
4  2.99           Teen

In [54]:
df.tail()

App      Category  Rating  Reviews                Size  Installs  Type  \
25  App_26          Game     4.5     9497                 30M    1,000+  Free   
26  App_27          Game     3.5       61                 30M  100,000+  Paid   
27  App_28        Health     1.9     5883  Varies with device   10,000+  Free   
28  App_29        Health     3.1     4672                 10M  100,000+  Free   
29  App_30  Productivity     4.4     4346  Varies with device    1,000+  Paid   

   Price Content Rating  
25  5.99           Teen  
26  9.99   Everyone 10+  
27  0.99   Everyone 10+  
28     0       Everyone  
29     0           Teen

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             30 non-null     object 
 1   Category        30 non-null     object 
 2   Rating          30 non-null     float64
 3   Reviews         30 non-null     int32  
 4   Size            30 non-null     object 
 5   Installs        30 non-null     object 
 6   Type            30 non-null     object 
 7   Price           30 non-null     object 
 8   Content Rating  30 non-null     object 
dtypes: float64(1), int32(1), object(7)
memory usage: 2.1+ KB


In [56]:
df.describe()

Rating      Reviews
count  30.000000    30.000000
mean    3.503333  5453.200000
std     0.863626  2882.471765
min     1.900000    61.000000
25%     2.950000  3592.500000
50%     3.500000  5593.500000
75%     4.300000  8191.250000
max     4.900000  9656.000000

In [57]:
#accessing assigned columns
df[['App','Reviews','Price']]   #single [] represents 1D which generates error

App  Reviews Price
0    App_1     6540  1.99
1    App_2     8216     0
2    App_3     3645  2.99
3    App_4     2421     0
4    App_5     5788  2.99
5    App_6     3575  4.99
6    App_7     6639  4.99
7    App_8     5959     0
8    App_9      446  9.99
9   App_10     3915  4.99
10  App_11     9656  9.99
11  App_12     6818     0
12  App_13     8117     0
13  App_14     2676  5.99
14  App_15     9184  9.99
15  App_16     4030  0.99
16  App_17     8800     0
17  App_18     5051     0
18  App_19     3434  2.99
19  App_20     8468  2.99
20  App_21     5399  4.99
21  App_22     8500  0.99
22  App_23     9590  5.99
23  App_24      434  2.99
24  App_25     1836  9.99
25  App_26     9497  5.99
26  App_27       61  9.99
27  App_28     5883  0.99
28  App_29     4672     0
29  App_30     4346     0

In [58]:
df.shape

(30, 9)

In [59]:
#unique values
df['Size'].unique()

array(['20M', '10M', 'Varies with device', '30M'], dtype=object)

In [60]:
df['Rating'].unique()

array([2.2, 3.3, 3.5, 4.6, 3.7, 3.4, 2.1, 4.4, 2.7, 2. , 4.9, 2.5, 3.9,
       3.1, 2.9, 3.8, 4. , 4.8, 4.5, 1.9])

In [62]:
df['Reviews'].unique()

array([6540, 8216, 3645, 2421, 5788, 3575, 6639, 5959,  446, 3915, 9656,
       6818, 8117, 2676, 9184, 4030, 8800, 5051, 3434, 8468, 5399, 8500,
       9590,  434, 1836, 9497,   61, 5883, 4672, 4346])

In [65]:
#checking null values
df.isnull()    #generaes boolean output

App  Category  Rating  Reviews   Size  Installs   Type  Price  \
0   False     False   False    False  False     False  False  False   
1   False     False   False    False  False     False  False  False   
2   False     False   False    False  False     False  False  False   
3   False     False   False    False  False     False  False  False   
4   False     False   False    False  False     False  False  False   
5   False     False   False    False  False     False  False  False   
6   False     False   False    False  False     False  False  False   
7   False     False   False    False  False     False  False  False   
8   False     False   False    False  False     False  False  False   
9   False     False   False    False  False     False  False  False   
10  False     False   False    False  False     False  False  False   
11  False     False   False    False  False     False  False  False   
12  False     False   False    False  False     False  False  False   
13  False     False   False    False  False     False  False  False   
14  False     False   False    False  False     False  False  False   
15  False     False   False    False  False     False  False  False   
16  False     False   False    False  False     False  False  False   
17  False     False   False    False  False     False  False  False   
18  False     False   False    False  False     False  False  False   
19  False     False   False    False  False     False  False  False   
20  False     False   False    False  False     False  False  False   
21  False     False   False    False  False     False  False  False   
22  False     False   False    False  False     False  False  False   
23  False     False   False    False  False     False  False  False   
24  False     False   False    False  False     False  False  False   
25  False     False   False    False  False     False  False  False   
26  False     False   False    False  False     False  False  False   
27  False     False   False    False  False     False  False  False   
28  False     False   False    False  False     False  False  False   
29  False     False   False    False  False     False  False  False   

    Content Rating  
0            False  
1            False  
2            False  
3            False  
4            False  
5            False  
6            False  
7            False  
8            False  
9            False  
10           False  
11           False  
12           False  
13           False  
14           False  
15           False  
16           False  
17           False  
18           False  
19           False  
20           False  
21           False  
22           False  
23           False  
24           False  
25           False  
26           False  
27           False  
28           False  
29           False

In [68]:
df.isnull().sum()   #generates number of null values

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
dtype: int64

In [69]:
#basic data cleansing or pre-processing
#df['Price'].replace('Free','0')    #changes only for this specific cell
df['Price'] = df['Price'].replace('Free','0')

In [70]:
df['Price']

0     1.99
1        0
2     2.99
3        0
4     2.99
5     4.99
6     4.99
7        0
8     9.99
9     4.99
10    9.99
11       0
12       0
13    5.99
14    9.99
15    0.99
16       0
17       0
18    2.99
19    2.99
20    4.99
21    0.99
22    5.99
23    2.99
24    9.99
25    5.99
26    9.99
27    0.99
28       0
29       0
Name: Price, dtype: object